/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dead_tree.glb 
Author: Inuciian (https://sketchfab.com/Inuciian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dead-tree-ccc4088f050a4f708f3855c71d2bd9c4
Title: Dead Tree
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DeadTree(props) {
  const { nodes, materials } = useGLTF("/models/dead_tree.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.dead_tree001_0.geometry}
          material={materials.wood_3_mat}
          position={[1.589, 15.542, -0.881]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/dead_tree.glb");
