/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dry_grass_2.glb 
Author: Inuciian (https://sketchfab.com/Inuciian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dry-grass-2-d1d1f44576fa4850911d33e83f70256f
Title: Dry Grass 2
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DryGrass(props) {
  const { nodes, materials } = useGLTF("/models/dry_grass.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.grass_1015_0.geometry}
          material={materials.autumn_yellow_mat}
          position={[-3.483, -0.328, 0.193]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/dry_grass.glb");
