/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 knight_character.glb 
Author: Inuciian (https://sketchfab.com/Inuciian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/knight-character-be8bb8a62e7d4ef7987bf3aba47ef7ce
Title: Knight Character
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function KnightCharacter(props) {
  const { scene } = useGLTF("/models/knight_character.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.06, 0.722]}>
          <primitive object={nodes.Armature_Knight_rootJoint} />
          <mesh
            geometry={nodes.knight_0.geometry}
            material={materials.knight_mat}
            position={[0, -0.121, -0.722]}
            rotation={[0, 0, -Math.PI]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/knight_character.glb");
