/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 monk_character.glb 
Author: Inuciian (https://sketchfab.com/Inuciian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/monk-character-8cacbd85a5b84f59a8c9000d7a6dcca2
Title: Monk Character
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function MonkCharacter(props) {
  const { scene } = useGLTF("/models/monk_character.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0.06, 0.722]}>
          <primitive object={nodes.Armature_Monk_rootJoint} />
          <mesh
            geometry={nodes.monk_0.geometry}
            material={materials.monk_material}
            position={[0, -0.121, -0.722]}
            rotation={[0, 0, -Math.PI]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/monk_character.glb");

useGLTF.preload("/monk_character.glb");
