/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 pine_tree.glb 
Author: Inuciian (https://sketchfab.com/Inuciian)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pine-tree-213783903af8483ea8a8187d307447c9
Title: Pine Tree
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PineTree(props) {
  const { nodes, materials } = useGLTF("/models/pine_tree.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.pine_tree_0.geometry}
          material={materials.tree_1_mat}
          position={[6.541, 15.14, 0.361]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/pine_tree.glb");
