/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rock.glb 
Author: Bull studios (https://sketchfab.com/dzemalmclaren)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/stylized-lowpoly-rock-6e476441b5614231bf4e8de194c418d9
Title: Stylized lowpoly rock
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Rock(props) {
  const { nodes, materials } = useGLTF("/models/rock.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.node_id4_Material_52_0.geometry}
        material={materials.Material_52}
        position={[-0.016, -0.013, 0.241]}
        rotation={[3.009, 0.274, -0.227]}
        scale={0.333}
      />
    </group>
  );
}

useGLTF.preload("/models/rock.glb");
